Simulation = "CosiProtocol"
Servers = 8
Bf = 4
Rounds = 10
CloseWait = 6000
Bandwidth = 10 # Mb/s, only in mininet
Delay = 50 # ms, only in mininet

Hosts, NSubtrees, FailingSubleaders,FailingLeafs
5, 1, 0, 0
5, 1, 1, 0
5, 2, 0, 2